### ISSUE TITLE
Failure to download certain courses (json.decoder.JSONDecodeError)

### ISSUE THREAD

**Issue by merberich** [FLZ101/dl_coursera#22]
I think Coursera may have updated their URL pathing for some of the newer courses - the response sometimes fails to decode into JSON properly, which means there's likely a problem fetching (resource at a different address perhaps).

Of note, it looks like there might be the same problem on the CI builds, so this is probably a change Coursera-side.

My command:
`dl_coursera --cookies cookies-coursera-org.txt --how curl --slug blockchain-revolution-enterprise --isSpec`

Partial traceback:
```
...
2021-11-06 14:21:22,925 - 1 - [Failed] priority=B, ttl=3. crawl_course: cource=blockchain-opportunity-analysis
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\dl_coursera\lib\TaskScheduler.py", line 167, in _func_work
    task.run()
  File "c:\python37\lib\site-packages\dl_coursera\lib\TaskScheduler.py", line 44, in run
    self.go()
  File "c:\python37\lib\site-packages\dl_coursera\lib\TaskScheduler.py", line 75, in go
    self._func(**self._kwargs)
  File "c:\python37\lib\site-packages\dl_coursera\Crawler.py", line 99, in crawl_course
    d = Crawler._get(sess, URL_COURSE_1(course['slug']))
  File "c:\python37\lib\site-packages\dl_coursera\Crawler.py", line 43, in _get
    d = resp.json()
  File "c:\python37\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "c:\python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "c:\python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\dl_coursera.exe\__main__.py", line 7, in <module>
  File "c:\python37\lib\site-packages\dl_coursera_run.py", line 178, in main
    soc = crawl(args['cookies'], args['slug'], args['isSpec'], args['outdir'], args['n_worker'])
  File "c:\python37\lib\site-packages\dl_coursera_run.py", line 71, in crawl
    soc = crawler.crawl(slug=slug, isSpec=isSpec)
  File "c:\python37\lib\site-packages\dl_coursera\Crawler.py", line 313, in crawl
    assert len(failures) == 0
AssertionError
```

The same JSONDecodeError repeats for all subsections after this line:
```
...
2021-11-06 14:21:15,786 - 1 - [Doing] priority=C, ttl=3. crawl_supplement: course=blockchain-business, supplement=opportunities-for-blockchain
2021-11-06 14:21:15,858 - 2 - [Done] priority=C, ttl=3. crawl_lecture: course=blockchain-business, lecture=hacking-your-future-boundary-decisions
2021-11-06 14:21:15,858 - 2 - [Doing] priority=C, ttl=3. crawl_lecture: course=blockchain-business, lecture=opportunity-4-building-trust
2021-11-06 14:21:15,867 - 1 - [Retry later] priority=C, ttl=3. crawl_supplement: course=blockchain-business, supplement=opportunities-for-blockchain
```

**Comment by asergeenko** [comment]
Same thing

**Comment by effy46** [comment]
It works for certain courses, but it failed for some other courses.

**Comment by FLZ101** [comment]
> Traceback (most recent call last):
>   File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\python37\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Python37\Scripts\dl_coursera.exe\__main__.py", line 7, in <module>
>   File "c:\python37\lib\site-packages\dl_coursera_run.py", line 178, in main
>     soc = crawl(args['cookies'], args['slug'], args['isSpec'], args['outdir'], args['n_worker'])
>   File "c:\python37\lib\site-packages\dl_coursera_run.py", line 71, in crawl
>     soc = crawler.crawl(slug=slug, isSpec=isSpec)
>   File "c:\python37\lib\site-packages\dl_coursera\Crawler.py", line 313, in crawl
>     assert len(failures) == 0
> AssertionError

Have you enrolled in the course/specilization before downloading it? Since people might forget to do that.

**Comment by FLZ101** [comment]
> 

Have you enrolled in the course/specilization before downloading it? Since people might forget to do that.

**Comment by FLZ101** [comment]
> It works for certain courses, but it failed for some other courses.

Have you enrolled in the course/specilization before downloading it? Since people might forget to do that.

**Comment by Bivishan1** [comment]
> > It works for certain courses, but it failed for some other courses.
> 
> Have you enrolled in the course/specilization before downloading it? Since people might forget to do that.

hey, it's only downloading the unnecessary resources file, showing following message in console:
`{'trackId': 'core', 'isLocked': False, 'name': 'Assembly Endgame Outro', 'lessonId': 'N44xq', 'timeCommitment': 60000, 'id': 'uMNxE', 'moduleId': 'I2YRg', 'contentSummary': {'typeName': 'ungradedWidget', 'definition': {'minWidthPx': 0, 'supportsTouch': True, 'minHeightPx': 0}}, 'slug': 'assembly-endgame-outro'}
2025-03-30 12:07:32,049 - 1 - [crawl_course] unknown typeName=staffGraded
{'trackId': 'core', 'isLocked': False, 'name': 'Assembly: Endgame Capstone Project Quiz', 'lessonId': 'N44xq', 'timeCommitment': 1800000, 'id': '4wu9t', 'moduleId': 'I2YRg', 'contentSummary': {'typeName': 'staffGraded', 'definition': {'isTeamSubmissionEnabled': False, 'standardProctorConfigurationId': 'STANDARD~wxay4KJ2Ee-uvQr_wp2rpw!~wxay4aJ2Ee-uvQr_wp2rpw@2', 'requiredMobileFeatures': []}}, 'slug': 'assembly-endgame-capstone-project-quiz'}
2025-03-30 12:07:32,050 - 1 - [crawl_course] unknown typeName=ungradedWidget
{'trackId': 'core', 'isLocked': False, 'name': 'Course Outro', 'lessonId': 'N44xq', 'timeCommitment': 420000, 'id': 'rebcI', 'moduleId': 'I2YRg', 'contentSummary': {'typeName': 'ungradedWidget', 'definition': {'minWidthPx': 0, 'supportsTouch': True, 'minHeightPx': 0}}, 'slug': 'course-outro'}
2025-03-30 12:07:32,050 - 1 - [Done] priority=B, ttl=3. crawl_course: cource=learn-react
2025-03-30 12:07:32,051 - 2 - [Doing] priority=C, ttl=3. crawl_course_references: cource=learn-react
2025-03-30 12:07:32,308 - 2 - [Done] priority=C, ttl=3. crawl_course_references: cource=learn-react
2025-03-30 12:07:32,388 - MainThread - new directory tree: F:\courses\testCoursera\dl_coursera\mt\learn-react\resource

Done :-)`
